PREFIX bds: <http://www.bigdata.com/rdf/search#>
PREFIX bk: <https://gams.uni-graz.at/rem/bookkeeping/#>
PREFIX t: <http://www.tei-c.org/ns/1.0/>

select distinct ?concept ?transfer ?entry ?text ?date ?from ?from_name ?to ?to_name ?measurable ?quantity ?unit ($1 as ?query)
{
   ?concept a $1.
   ?transfer ?b ?concept.
  
    OPTIONAL{
      ?transfer  bk:from ?from.
      ?from bk:name ?from_name.  
    }
    OPTIONAL{
      ?transfer  bk:from ?to.
      ?to bk:name ?to_name.  
    }
    OPTIONAL
  	{       
     ?transfer bk:hasDate ?date.    
    }
   OPTIONAL
  	{       
     ?transfer bk:transfers ?measurable.
     ?measurable bk:quantity ?quantity;
                 bk:unit ?unit.
    }
  
   ?transfer bk:hasEntry ?entry.
  
   OPTIONAL{?entry  bk:hasText ?text}
   
  
}
