PREFIX bds: <http://www.bigdata.com/rdf/search#>
PREFIX bk: <https://gams.uni-graz.at/rem/bookkeeping/#>
PREFIX t: <http://www.tei-c.org/ns/1.0/>

#author:Christopher pollin
#Select all Accounts (bk:Between) which have a value ?quantity in there ?MonetaryValue 
# and which have a date/@when

select distinct ?category ?when
{
  ?category a bk:Between.
  ?a ?b ?category.
  ?a bk:transfers ?MonetaryValue.
  ?a bk:when ?when.
  ?MonetaryValue bk:quantity ?quantity.
  ?MonetaryValue bk:unit ?unit.

  
	
}
