PREFIX bds: <http://www.bigdata.com/rdf/search#>
PREFIX bk: <https://gams.uni-graz.at/o:depcha.bookkeeping#>
PREFIX t: <http://www.tei-c.org/ns/1.0/>
PREFIX gams:<https://gams.uni-graz.at/o:gams-ontology/#>

#author:Georg Vogeler
#param: $1 = URI of data set = Collection, referenced by gams:isMemberOfCollection, e.g. <https://gams.uni-graz.at/context:depcha.wheaton>

SELECT  (?Commodity as ?name) (count(?Entry) as ?size) (str(?q) as ?query)
WHERE {
  BIND($1 as ?q)
  ?Transaction bk:entry ?Entry .
  ?Transaction gams:isMemberOfCollection ?q .
  ?Transaction gams:isMemberOfCollection ?Collection .
  ?Collection bk:name ?Collection_name .
  ?Transaction bk:consistsOf ?Transfer .
  ?Transfer bk:transfers ?Measurable .
  ?Measurable bk:commodity ?Commodity .
}
GROUP BY ?Commodity ?q